export const REQUEST_PENDING = 'REQUEST_STUDENTS_PENDING';
export const REQUEST_STUDENTS_SUCCESS = 'REQUEST_STUDENTS_SUCCESS';
export const REQUEST_FAILED = 'REQUEST_STUDENTS_FAILED';
export const REQUEST_SUBJECT_SUCCESS = 'REQUEST_SUBJECT_SUCCESS';
export const REQUEST_SESSION_SUCCESS = 'REQUEST_SESSION_SUCCESS';
export const REQUEST_SEMESTER_SUCCESS = 'REQUEST_SEMESTER_SUCCESS';
export const REQUEST_FACULTY_SUCCESS = 'REQUEST_FACULTY_SUCCESS';
export const REQUEST_COURSE_SUCCESS = 'REQUEST_COURSE_SUCCESS';
export const REQUEST_GROUP_SUCCESS = 'REQUEST_GROUP_SUCCESS';

export const REQUEST_ATTENDANCE_LINE_SUCCESS = 'REQUEST_ATTENDANCE_LINE_SUCCESS';
export const REQUEST_ATTENDANCE_LINE_PENDING = 'REQUEST_ATTENDNACE_LINE_PENDING';
export const REQUEST_ATTENDANCE_LINE_FAILED = 'REQUEST_ATTENDANCE_LINE_FAILED';

export const CHANGE_BATCH = 'CHANGE_BATCH'
export const CHANGE_SUBJECT = 'CHANGE_SUBJECT'
export const CHANGE_SESSION = 'CHANGE_SESSION'
export const CHANGE_DATE = 'CHANGE_DATE'
export const CHANGE_REMARK = 'CHANGE_REMARK'
export const CHANGE_COURSE = 'CHANGE_COURSE'
export const CHANGE_SEMESTER = 'CHANGE_SEMESTER'
export const CHANGE_FACULTY = 'CHANGE_FACULTY'
export const CHANGE_GROUP = 'CHANGE_GROUP'
export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'