export const REQUEST_STUDENTS_PENDING = 'REQUEST_STUDENTS_PENDING';
export const REQUEST_STUDENTS_SUCCESS = 'REQUEST_STUDENTS_SUCCESS';
export const REQUEST_STUDENTS_FAILED = 'REQUEST_STUDENTS_FAILED';
export const CHANGE_BATCH = 'CHANGE_BATCH'